### ISSUE TITLE
make demo-server docker image

### ISSUE THREAD

**Issue by brollb** [deepforge-dev/examples#15]
Docker-compose up is really slow since it needs to install the deepforge-keras extension. We should just make a new server image which has it preinstalled.

**Comment by umesh-timalsina** [comment]
I am digging into this and will update the docker-images accordingly.

**Comment by brollb** [comment]
This has been resolved in https://github.com/deepforge-dev/deepforge

**Comment by brollb** [comment]
For the record, the "demo-server" image is called "kitchen-sink" (https://github.com/deepforge-dev/deepforge/blob/master/docker/docker-compose.yml#L15)
